name: Build Wheel

on:
  push:
    branches:
      - main

env:
  MACOSX_DEPLOYMENT_TARGET: "10.15"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2019, macos-13]

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/checkout@v4

      - name: Set up Visual Studio shell on Windows
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: set x64 cl.exe as CXX
        if: matrix.os == 'windows-2022'
        run: |
          "CXX=$((Get-Command cl).Path)" >> "$env:GITHUB_ENV"
          "CC=$((Get-Command cl).Path)" >> "$env:GITHUB_ENV"

      - name: select Xcode version
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          sudo xcode-select -s "/Applications/Xcode_14.3.app"

      - name: Update pip
        run: python -m pip install -U pip

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5

      - name: Build Wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: ${{ matrix.os }}
